# Generated by Django 4.2 on 2023-06-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
